'use client'

import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { generateColormindPaletteByStyle } from '@/lib/apis/colormind'
import { generateDesignTips } from '@/lib/apis/groq'

type Palette = {
  colors: Array<{
    name: string
    hex: string
    usage: string
  }>
  description: string
  mood: string
} | null

const industries = [
  'Technology',
  'Finance',
  'Healthcare',
  'E-commerce',
  'Fitness',
  'Fashion',
  'Food & Beverage',
  'Real Estate',
]

const moods = [
  'Professional',
  'Creative',
  'Playful',
  'Minimalist',
  'Luxurious',
  'Energetic',
  'Calming',
  'Bold',
]

const colorNames = ['Primary', 'Secondary', 'Tertiary', 'Accent', 'Supporting']
const colorUsages = [
  'Main brand color',
  'Accents and highlights',
  'Supporting elements',
  'Interactive elements',
  'Background accents',
]

export default function ColorPaletteGenerator() {
  const [industry, setIndustry] = useState(industries[0])
  const [mood, setMood] = useState(moods[0])
  const [palette, setPalette] = useState<Palette>(null)
  const [loading, setLoading] = useState(false)
  const [designTips, setDesignTips] = useState<string>('')
  const [copiedColor, setCopiedColor] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  const generatePalette = async () => {
    setLoading(true)
    setError(null)
    try {
      // Use Colormind API for AI-powered color generation
      const style = mood === 'Professional' || mood === 'Minimalist' ? 'ui' : 'painting'
      const colormindPalette = await generateColormindPaletteByStyle(style)

      // Create palette object with names and usage descriptions
      const newPalette: Palette = {
        colors: colormindPalette.colors.map((hex, index) => ({
          name: colorNames[index % colorNames.length],
          hex,
          usage: colorUsages[index % colorUsages.length],
        })),
        description: `AI-powered ${mood.toLowerCase()} color palette optimized for ${industry}. Generated by Colormind.`,
        mood,
      }

      setPalette(newPalette)

      // Get AI design tips using Groq
      try {
        const tips = await generateDesignTips(
          colormindPalette.colors,
          ['Poppins', 'Inter']
        )
        setDesignTips(tips)
      } catch (tipError) {
        console.error('Error getting design tips:', tipError)
        // Continue without tips
      }
    } catch (err) {
      setError('Failed to generate palette. Please try again.')
      console.error('Error generating palette:', err)
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = (hex: string) => {
    navigator.clipboard.writeText(hex)
    setCopiedColor(hex)
    setTimeout(() => setCopiedColor(null), 2000)
  }

  return (
    <div className="space-y-8">
      {/* Controls */}
      <div className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <label className="block text-sm font-medium mb-3">Industry</label>
            <select
              value={industry}
              onChange={(e) => setIndustry(e.target.value)}
              className="w-full px-4 py-3 bg-background border border-border rounded-lg focus:border-accent focus:outline-none transition-colors"
            >
              {industries.map((ind) => (
                <option key={ind} value={ind}>
                  {ind}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium mb-3">Mood</label>
            <select
              value={mood}
              onChange={(e) => setMood(e.target.value)}
              className="w-full px-4 py-3 bg-background border border-border rounded-lg focus:border-accent focus:outline-none transition-colors"
            >
              {moods.map((m) => (
                <option key={m} value={m}>
                  {m}
                </option>
              ))}
            </select>
          </div>
        </div>

        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          onClick={generatePalette}
          disabled={loading}
          className="w-full px-6 py-4 bg-primary text-primary-foreground rounded-lg font-semibold hover:bg-primary/90 transition-colors disabled:opacity-50"
        >
          {loading ? 'Generating...' : 'Generate Palette'}
        </motion.button>
      </div>

      {/* Error Display */}
      {error && (
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-4 bg-destructive/10 border border-destructive text-destructive rounded-lg"
        >
          {error}
        </motion.div>
      )}

      {/* Palette Display */}
      {palette && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-6"
        >
          {/* Palette Info */}
          <div>
            <h3 className="text-lg font-bold mb-2">{palette.mood} Palette</h3>
            <p className="text-muted-foreground">{palette.description}</p>
          </div>

          {/* Design Tips from AI */}
          {designTips && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="p-4 bg-primary/10 border border-primary/30 rounded-lg space-y-2"
            >
              <p className="text-sm font-semibold text-accent">AI Design Tips:</p>
              <p className="text-sm text-muted-foreground whitespace-pre-line">{designTips}</p>
            </motion.div>
          )}

          {/* Color Swatches */}
          <div className="space-y-3">
            {palette.colors.map((color) => (
              <motion.div
                key={color.hex}
                whileHover={{ scale: 1.02 }}
                onClick={() => copyToClipboard(color.hex)}
                className="cursor-pointer group"
              >
                <div className="flex items-center gap-4 p-4 rounded-lg border border-border hover:border-accent transition-colors">
                  <div
                    className="w-20 h-20 rounded-lg shadow-lg"
                    style={{ backgroundColor: color.hex }}
                  />
                  <div className="flex-1">
                    <p className="font-semibold">{color.name}</p>
                    <p className="text-sm text-muted-foreground mb-2">{color.hex}</p>
                    <p className="text-sm text-muted-foreground">{color.usage}</p>
                  </div>
                  <motion.div
                    initial={{ opacity: 0 }}
                    whileHover={{ opacity: 1 }}
                    className="px-3 py-2 bg-primary/20 text-accent rounded text-sm font-medium"
                  >
                    {copiedColor === color.hex ? '✓ Copied' : 'Copy'}
                  </motion.div>
                </div>
              </motion.div>
            ))}
          </div>

          {/* Export Options */}
          <div className="pt-4 border-t border-border space-y-3">
            <p className="text-sm text-muted-foreground">Export your palette:</p>
            <div className="flex gap-3 flex-wrap">
              <button className="px-4 py-2 bg-primary/20 text-accent rounded-lg text-sm font-medium hover:bg-primary/30 transition-colors">
                Export as CSS
              </button>
              <button className="px-4 py-2 bg-primary/20 text-accent rounded-lg text-sm font-medium hover:bg-primary/30 transition-colors">
                Export as JSON
              </button>
              <button className="px-4 py-2 bg-primary/20 text-accent rounded-lg text-sm font-medium hover:bg-primary/30 transition-colors">
                Export as Figma
              </button>
            </div>
          </div>
        </motion.div>
      )}

      {/* Placeholder */}
      {!palette && !loading && !error && (
        <div className="text-center py-12">
          <p className="text-muted-foreground mb-6">
            Select an industry and mood, then generate your AI-powered color palette using Colormind.
          </p>
          <div className="inline-block text-5xl">🎨</div>
        </div>
      )}
    </div>
  )
}
